AWSTemplateFormatVersion: '2010-09-09'
Description: Production stack with VPC, Subnet, Security Group, Launch Template, and Auto Scaling Group

Resources:

  ProdVPC:
    Type: AWS::EC2::VPC
    DeletionPolicy: Retain
    Properties:
      CidrBlock: 10.20.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: prod-vpc

  ProdSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ProdVPC
      CidrBlock: 10.20.1.0/24
      AvailabilityZone: eu-central-1a
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: prod-subnet

  ProdSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP access
      VpcId: !Ref ProdVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  ProdLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: prod-launch-template
      LaunchTemplateData:
        KeyName: dev-key2
        ImageId: ami-0f78f0f0c76cef16f
        InstanceType: t3.micro
        SecurityGroupIds:
          - !Ref ProdSG
        UserData:
          Fn::Base64:
            !Sub |
              #!/bin/bash
              yum update -y
              yum install -y httpd
              systemctl enable httpd
              systemctl start httpd

              # FORCE UPDATE: include timestamp so a new LT version is ALWAYS created
              echo "<h1>Welcome to PROD at ${AWS::Timestamp}</h1>" > /var/www/html/index.html

  ProdASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: 0
        MaxBatchSize: 1
        PauseTime: PT0S
        WaitOnResourceSignals: false
    Properties:
      MinSize: 1
      MaxSize: 3
      DesiredCapacity: 1
      LaunchTemplate:
        LaunchTemplateId: !Ref ProdLaunchTemplate
        Version: !GetAtt ProdLaunchTemplate.LatestVersionNumber
      VPCZoneIdentifier:
        - !Ref ProdSubnet
      Tags:
        - Key: Name
          Value: prod-instance
          PropagateAtLaunch: true

Outputs:
  VPCId:
    Value: !Ref ProdVPC
  SubnetId:
    Value: !Ref ProdSubnet
  SecurityGroupId:
    Value: !Ref ProdSG
  LaunchTemplateId:
    Value: !Ref ProdLaunchTemplate